---
apiVersion: v1
kind: Service
metadata:
    name: training-service
    labels:
        app: training
spec:
    selector:
        app: training
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080